name: Testes Automatizados com Jest

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  testes:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Instalar dependências
      run: npm install

    - name: Rodar testes com Jest e gerar cobertura
      run: npm test -- --coverage

    - name: Enviar relatório de cobertura para o Codecov (opcional)
      uses: codecov/codecov-action@v3